### ISSUE TITLE
Paradox Mods Compatibility

### ISSUE THREAD

**Issue by dominguesg** [johnytoxic/CSL2DemandControl#12]
Is it possible to add this mod to Paradox Mods?

Thank you for this wonderful mod.

**Comment by johnytoxic** [comment]
Thanks for the interest! I plan on publishing this mod on the official store soon!

**Comment by johnytoxic** [comment]
I've just published the mod to Paradox Mods: https://mods.paradoxplaza.com/mods/77901/Windows.
