### ISSUE TITLE
Population bug

### ISSUE THREAD

**Issue by sebas1490865** [johnytoxic/CSL2DemandControl#4]
Ok so the mod works but theres this one problem, houses rarely got any population and after some time theres gonna be a huge abandoned houses wave

**Comment by johnytoxic** [comment]
This is a duplicate of #1, lease see my [latest comment](https://github.com/johnytoxic/CSL2DemandControl/issues/1#issuecomment-1859211115).

Please download the latest version (just published) and check whether that fixes the issue.
